// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///flutter pub get
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxs6w6nV4b4Rg2AhZS-qMymKC9SePal00',
    appId: '1:680915154108:web:5852fa8a503e94c0a90cb9',
    messagingSenderId: '680915154108',
    projectId: 'veloce-6e91d',
    authDomain: 'veloce-6e91d.firebaseapp.com',
    storageBucket: 'veloce-6e91d.firebasestorage.app',
    measurementId: 'G-G27YV55ER3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7komFGGkywgtLSZ3YRBGF88gYjDtjuOs',
    appId: '1:680915154108:android:7d0364c770800f78a90cb9',
    messagingSenderId: '680915154108',
    projectId: 'veloce-6e91d',
    storageBucket: 'veloce-6e91d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00GzhpiL2lf4uhx3Dxl1AvV2_RB3W7nM',
    appId: '1:680915154108:ios:0bb5f52b6c07521ea90cb9',
    messagingSenderId: '680915154108',
    projectId: 'veloce-6e91d',
    storageBucket: 'veloce-6e91d.firebasestorage.app',
    iosBundleId: 'com.example.veloceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD00GzhpiL2lf4uhx3Dxl1AvV2_RB3W7nM',
    appId: '1:680915154108:ios:0bb5f52b6c07521ea90cb9',
    messagingSenderId: '680915154108',
    projectId: 'veloce-6e91d',
    storageBucket: 'veloce-6e91d.firebasestorage.app',
    iosBundleId: 'com.example.veloceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxs6w6nV4b4Rg2AhZS-qMymKC9SePal00',
    appId: '1:680915154108:web:ff9c1b500a6d9b34a90cb9',
    messagingSenderId: '680915154108',
    projectId: 'veloce-6e91d',
    authDomain: 'veloce-6e91d.firebaseapp.com',
    storageBucket: 'veloce-6e91d.firebasestorage.app',
    measurementId: 'G-N0WMXEYFMJ',
  );
}
